spring:
  application:
    name: user-service
  profiles:
    active: default
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://host.docker.internal:5435/ticketing-app
    username: postgres
    password: Asiye1013+
    driver-class-name: org.postgresql.Driver
server:
  port: 9090
eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/info
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

